[package]
name = "renderia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
env_logger = "0.10.1"
thiserror = "1.0.50"
gl = "0.14.0"
glam = "0.24.2"
glfw = "0.54.0"
image = "0.24.7"
